// This file is now used for seeding the database only.
// The application fetches data from Firestore.

import type { Product, Artisan } from './types';

// The ID property is not needed here as Firestore will generate it.
// However, to maintain the relationship, we use a temporary, predictable ID
// that will be replaced during the actual seeding process in firestore.ts.
export const artisans: Omit<Artisan, 'id'>[] = [
  {
    name: 'Priya Sharma',
    name_hi: 'प्रिया शर्मा',
    bio: 'Priya is a third-generation block-printer from Jaipur, a city renowned for its vibrant textiles. She finds inspiration in the intricate patterns of Rajasthani architecture and nature. Each piece is a testament to the timeless tradition of Sanganeri block-printing, crafted with passion and precision.',
    bio_hi: 'प्रिया जयपुर की तीसरी पीढ़ी की ब्लॉक-प्रिंटर हैं, जो अपने जीवंत वस्त्रों के लिए प्रसिद्ध शहर है। वह राजस्थानी वास्तुकला और प्रकृति के जटिल पैटर्न से प्रेरणा पाती हैं। प्रत्येक टुकड़ा सांगानेरी ब्लॉक-प्रिंटिंग की कालातीत परंपरा का एक प्रमाण है, जिसे जुनून और सटीकता के साथ तैयार किया गया है।',
    profileImage: 'https://image2url.com/images/1755014190052-e7330edb-abfe-45c3-af51-543a4ea9fddf.png',
    location: 'Jaipur, Rajasthan',
    location_hi: 'जयपुर, राजस्थान',
    craft: 'Block-Printing',
    craft_hi: 'ब्लॉक-प्रिंटिंग',
  },
  {
    name: 'Rohan Mehra',
    name_hi: 'रोहन मेहरा',
    bio: 'From his workshop in Saharanpur, Rohan Mehra practices the art of wood carving, a skill passed down through generations. He specializes in creating intricate home goods from Sheesham wood, using traditional techniques. His philosophy is to let the natural beauty of the wood speak for itself.',
    bio_hi: 'सहारनपुर में अपनी कार्यशाला से, रोहन मेहरा लकड़ी की नक्काशी की कला का अभ्यास करते हैं, जो पीढ़ियों से चली आ रही एक कौशल है। वह पारंपरिक तकनीकों का उपयोग करके शीशम की लकड़ी से जटिल घरेलू सामान बनाने में माहिर हैं। उनका दर्शन लकड़ी की प्राकृतिक सुंदरता को अपने लिए बोलने देना है।',
    profileImage: 'https://image2url.com/images/1755015058938-f2672261-043e-4567-ba9e-d3104222a788.png',
    location: 'Saharanpur, Uttar Pradesh',
    location_hi: 'सहारनपुर, उत्तर प्रदेश',
    craft: 'Wood Carving',
    craft_hi: 'लकड़ी की नक्काशी',
  },
  {
    name: 'Aisha Begum',
    name_hi: 'आइशा बेगम',
    bio: 'Aisha is a master of Chikankari embroidery from Lucknow. Her delicate and precise needlework brings traditional Mughal-era designs to life on fine fabrics. Each garment tells a story, stitched with threads of history and culture.',
    bio_hi: 'आइशा लखनऊ से चिकनकारी कढ़ाई की उस्ताद हैं। उनकी नाजुक और सटीक सुई का काम पारंपरिक मुगल-युग के डिजाइनों को महीन कपड़ों पर जीवंत करता है। प्रत्येक परिधान एक कहानी कहता है, जिसे इतिहास और संस्कृति के धागों से सिला गया है।',
    profileImage: 'https://image2url.com/images/1755015144032-3afa0c70-9c71-45f2-aefa-784b813d46a6.png',
    location: 'Lucknow, Uttar Pradesh',
    location_hi: 'लखनऊ, उत्तर प्रदेश',
    craft: 'Embroidery',
    craft_hi: 'कढ़ाई',
  },
];

export const products: Omit<Product, 'id'>[] = [
  {
    name: 'Hand-Blocked Table Runner',
    name_hi: 'हैंड-ब्लॉक टेबल रनर',
    description: 'A beautifully handcrafted table runner, perfect for adding a touch of Rajasthani elegance to your dining table. Features a classic floral motif in indigo and white.',
    description_hi: 'एक खूबसूरती से दस्तकारी टेबल रनर, जो आपके डाइनिंग टेबल में राजस्थानी लालित्य का स्पर्श जोड़ने के लिए एकदम सही है। इसमें इंडिगो और सफेद रंग में एक क्लासिक पुष्प रूपांकन है।',
    price: 2500.0,
    images: ['https://image2url.com/images/1755012548151-37da720e-1283-4244-8dca-c47b3c720224.webp', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    artisanId: 'artisan-1', // This will be replaced with real ID after seeding
    category: 'Block-Printing',
    category_hi: 'ब्लॉक-प्रिंटिंग',
    stock: 15,
    materials: ['Cotton Canvas', 'Natural Dyes'],
    materials_hi: ['कॉटन कैनवास', 'प्राकृतिक रंग'],
  },
  {
    name: 'Sheesham Wood Spice Box',
    name_hi: 'शीशम लकड़ी मसाला बॉक्स',
    description: 'An intricately carved "masala dabba" made from durable Sheesham wood. It features multiple compartments and a small spoon for your essential spices.',
    description_hi: 'टिकाऊ शीशम की लकड़ी से बना एक जटिल नक्काशीदार "मसाला डब्बा"। इसमें आपके आवश्यक मसालों के लिए कई डिब्बे और एक छोटा चम्मच है।',
    price: 3200.0,
    images: ['https://image2url.com/images/1755012697263-f3ecde05-3747-4697-81f3-54a09b3f9fc6.png', 'https://placehold.co/600x600.png'],
    artisanId: 'artisan-2',
    category: 'Wood Carving',
    category_hi: 'लकड़ी की नक्काशी',
    stock: 8,
    materials: ['Sheesham (Indian Rosewood)', 'Brass Inlay'],
    materials_hi: ['शीशम (भारतीय शीशम)', 'पीतल की जड़ाई'],
  },
  {
    name: 'Chikankari Cotton Kurta',
    name_hi: 'चिकनकारी कॉटन कुर्ता',
    description: 'A luxuriously soft cotton kurta featuring delicate Chikankari embroidery. The timeless floral patterns make it a versatile piece for any occasion.',
    description_hi: 'एक शानदार नरम सूती कुर्ता जिसमें नाजुक चिकनकारी कढ़ाई है। कालातीत पुष्प पैटर्न इसे किसी भी अवसर के लिए एक बहुमुखी टुकड़ा बनाते हैं।',
    price: 4500.0,
    images: ['https://image2url.com/images/1755012612654-0119e2d3-3168-4b58-800f-e27475e1889a.jpg'],
    artisanId: 'artisan-3',
    category: 'Embroidery',
    category_hi: 'कढ़ाई',
    stock: 5,
    materials: ['Mulmul Cotton', 'Cotton Thread'],
    materials_hi: ['मलमल कॉटन', 'कॉटन थ्रेड'],
  },
  {
    name: 'Sanganeri Print Cushion Covers',
    name_hi: 'सांगानेरी प्रिंट कुशन कवर',
    description: 'Set of two cotton cushion covers with a traditional Sanganeri bootis (small floral motif) print. Brightens up any living space instantly.',
    description_hi: 'पारंपरिक सांगानेरी बूटी (छोटे पुष्प रूपांकन) प्रिंट के साथ दो सूती कुशन कवर का सेट। किसी भी रहने की जगह को तुरंत रोशन करता है।',
    price: 1800.0,
    images: ['https://image2url.com/images/1755012784019-66a06b22-a636-4237-9af6-6be22db539c4.jpg'],
    artisanId: 'artisan-1',
    category: 'Block-Printing',
    category_hi: 'ब्लॉक-प्रिंटिंग',
    stock: 25,
    materials: ['Cotton Duck Fabric', 'Natural Dyes'],
    materials_hi: ['कॉटन डक फैब्रिक', 'प्राकृतिक रंग'],
  },
  {
    name: 'Hand-Carved Elephant Figurine',
    name_hi: 'हाथ से नक्काशीदार हाथी की मूर्ति',
    description: 'A symbol of wisdom and strength, this elegant elephant figurine is hand-carved from a single block of wood with remarkable detail.',
    description_hi: 'ज्ञान और शक्ति का प्रतीक, यह सुरुचिपूर्ण हाथी की मूर्ति उल्लेखनीय विस्तार के साथ लकड़ी के एक ही ब्लॉक से हाथ से बनाई गई है।',
    price: 2800.0,
    images: ['https://image2url.com/images/1755015650198-5f686942-17c1-43a9-9cda-25f82ea6756a.jpg'],
    artisanId: 'artisan-2',
    category: 'Wood Carving',
    category_hi: 'लकड़ी की नक्काशी',
    stock: 12,
    materials: ['Acacia Wood', 'Beeswax Finish'],
    materials_hi: ['बबूल की लकड़ी', 'मधुमक्खी के मोम की फिनिश'],
  },
  {
    name: 'Embroidered Silk Potli Bag',
    name_hi: 'कढ़ाई वाली सिल्क पोटली बैग',
    description: 'A vibrant silk potli (drawstring) bag, exquisitely embroidered with Zardozi work. The perfect accessory for weddings and festive occasions.',
    description_hi: 'एक जीवंत रेशम पोटली (ड्रॉस्ट्रिंग) बैग, जरदोजी के काम से उत्कृष्ट रूप से कढ़ाई की गई है। शादियों और उत्सव के अवसरों के लिए एकदम सही सहायक।',
    price: 2200.0,
    images: ['https://image2url.com/images/1755015552322-cc35871d-e350-4d58-ade2-4ef746cfe6d2.jpg'],
    artisanId: 'artisan-3',
    category: 'Embroidery',
    category_hi: 'कढ़ाई',
    stock: 20,
    materials: ['Raw Silk', 'Zari Thread', 'Beads'],
    materials_hi: ['कच्चा रेशम', 'जरी धागा', 'मोती'],
  },
   {
    name: 'Jaipuri Blue Pottery Vase',
    name_hi: 'जयपुरी ब्लू पॉटरी फूलदान',
    description: 'A classic blue pottery vase from Jaipur, featuring a traditional peacock design. Does not use regular clay, but a mix of quartz stone powder, powdered glass, and other materials.',
    description_hi: 'जयपुर का एक क्लासिक नीला मिट्टी का फूलदान, जिसमें एक पारंपरिक मोर डिजाइन है। नियमित मिट्टी का उपयोग नहीं करता है, बल्कि क्वार्ट्ज पत्थर पाउडर, पाउडर ग्लास और अन्य सामग्रियों का मिश्रण है।',
    price: 3500.0,
    images: ['https://image2url.com/images/1755015513823-5d8c1f61-2e1d-4788-91e6-8983754627f2.jpg'],
    artisanId: 'artisan-1',
    category: 'Pottery',
    category_hi: 'मिट्टी के बर्तन',
    stock: 10,
    materials: ['Quartz Powder', 'Lead-free Glaze'],
    materials_hi: ['क्वार्ट्ज पाउडर', 'सीसा रहित ग्लेज'],
  },
  {
    name: 'Wooden Jharokha Wall Decor',
    name_hi: 'लकड़ी का झरोखा दीवार की सजावट',
    description: 'A miniature, intricately carved "jharokha" (ornate window) that brings a piece of Rajasthani palaces to your wall. A stunning piece of craftsmanship.',
    description_hi: 'एक लघु, जटिल नक्काशीदार "झरोखा" (अलंकृत खिड़की) जो आपकी दीवार पर राजस्थानी महलों का एक टुकड़ा लाता है। शिल्प कौशल का एक आश्चर्यजनक टुकड़ा।',
    price: 7500.0,
    images: ['https://image2url.com/images/1755015585603-2034804a-c6fc-4547-8bfe-659efb18f352.jpg'],
    artisanId: 'artisan-2',
    category: 'Wood Carving',
    category_hi: 'लकड़ी की नक्काशी',
    stock: 7,
    materials: ['Mango Wood', 'Natural Varnish'],
    materials_hi: ['आम की लकड़ी', 'प्राकृतिक वार्निश'],
  },
];
