import type { Product, Artisan } from './types';

export const artisans: Artisan[] = [
  {
    id: 'artisan-1',
    name: 'Elena Rodriguez',
    bio: 'Elena is a third-generation ceramicist from a small village in Spain. She finds inspiration in the Mediterranean landscape, and her work is characterized by its organic shapes and earthy glazes. Each piece is a testament to the timeless tradition of pottery, crafted with passion and precision.',
    profileImage: 'https://placehold.co/400x400.png',
    location: 'Valencia, Spain',
    craft: 'Ceramics',
  },
  {
    id: 'artisan-2',
    name: 'Kenji Tanaka',
    bio: 'From his workshop in Kyoto, Kenji Tanaka practices the ancient art of woodworking. He specializes in creating intricate home goods using traditional Japanese joinery techniques, which require no nails or screws. His philosophy is to let the natural beauty of the wood speak for itself.',
    profileImage: 'https://placehold.co/400x400.png',
    location: 'Kyoto, Japan',
    craft: 'Woodworking',
  },
  {
    id: 'artisan-3',
    name: 'Amina Yusuf',
    bio: 'Amina is a weaver from Marrakesh, Morocco, who creates stunning textiles on a traditional loom. Her designs are inspired by Berber symbolism and the vibrant colors of her city. Each rug and tapestry tells a story, woven with threads of history and culture.',
    profileImage: 'https://placehold.co/400x400.png',
    location: 'Marrakesh, Morocco',
    craft: 'Textiles',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Earthenware Serving Bowl',
    description: 'A beautifully handcrafted serving bowl, perfect for salads, pasta, or as a stunning centerpiece. Glazed in a deep sea blue, reminiscent of the Spanish coast.',
    price: 75.0,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    artisanId: 'artisan-1',
    category: 'Ceramics',
    stock: 15,
    materials: ['Stoneware Clay', 'Lead-free Glaze'],
  },
  {
    id: 'prod-2',
    name: 'Hinoki Wood Cutting Board',
    description: 'A durable and aromatic cutting board made from a single piece of Hinoki cypress. Its natural oils have antibacterial properties, and its smooth surface is gentle on your knives.',
    price: 120.0,
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    artisanId: 'artisan-2',
    category: 'Woodworking',
    stock: 8,
    materials: ['Hinoki Cypress Wood', 'Natural Oil Finish'],
  },
  {
    id: 'prod-3',
    name: 'Berber Wool Throw Blanket',
    description: 'A luxuriously soft throw blanket woven from 100% natural wool. Adorned with traditional Berber patterns in black and cream, it adds a touch of Moroccan elegance to any room.',
    price: 250.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-3',
    category: 'Textiles',
    stock: 5,
    materials: ['Natural Wool', 'Vegetable Dyes'],
  },
  {
    id: 'prod-4',
    name: 'Hand-thrown Coffee Mugs',
    description: 'Set of two rustic coffee mugs, each with a unique, comfortable handle and a speckled oatmeal glaze. Perfect for your morning ritual.',
    price: 55.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-1',
    category: 'Ceramics',
    stock: 25,
    materials: ['Porcelain Clay', 'Lead-free Glaze'],
  },
  {
    id: 'prod-5',
    name: 'Minimalist Walnut Desk Organizer',
    description: 'Keep your desk tidy with this elegant organizer. Crafted from solid walnut with clean lines and simple compartments for your pens and essentials.',
    price: 90.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-2',
    category: 'Woodworking',
    stock: 12,
    materials: ['Walnut Wood', 'Beeswax Finish'],
  },
  {
    id: 'prod-6',
    name: 'Hand-dyed Silk Scarf',
    description: 'A vibrant silk scarf dyed with natural indigo. The shibori technique creates a unique, wave-like pattern, making each piece one-of-a-kind.',
    price: 85.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-3',
    category: 'Textiles',
    stock: 20,
    materials: ['100% Silk', 'Natural Indigo Dye'],
  },
   {
    id: 'prod-7',
    name: 'Small Terracotta Planter',
    description: 'A simple yet elegant terracotta planter, ideal for succulents or small house plants. Features a drainage hole and matching saucer.',
    price: 35.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-1',
    category: 'Ceramics',
    stock: 30,
    materials: ['Terracotta Clay'],
  },
  {
    id: 'prod-8',
    name: 'Japanese Tea Box',
    description: 'An airtight tea box made from cherry wood, perfect for storing your favorite loose-leaf teas. The precise fit of the lid showcases expert craftsmanship.',
    price: 150.0,
    images: ['https://placehold.co/600x600.png'],
    artisanId: 'artisan-2',
    category: 'Woodworking',
    stock: 7,
    materials: ['Cherry Wood', 'Natural Lacquer'],
  },
];
